# Generated by Django 5.0 on 2024-12-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HorseAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("horse_name", models.CharField(max_length=100, verbose_name="馬名")),
                ("race_count", models.IntegerField(verbose_name="出走回数")),
                ("win_count", models.IntegerField(verbose_name="1着回数")),
                ("second_count", models.IntegerField(verbose_name="2着回数")),
                ("third_count", models.IntegerField(verbose_name="3着回数")),
                ("win_rate", models.FloatField(verbose_name="勝率")),
                ("rentai_rate", models.FloatField(verbose_name="連対率")),
                ("fukusho_rate", models.FloatField(verbose_name="複勝率")),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="最終更新日"),
                ),
            ],
            options={
                "verbose_name": "競走馬分析",
                "verbose_name_plural": "競走馬分析一覧",
            },
        ),
    ]
