# Generated by Django 5.0 on 2024-12-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="horseanalysis",
            name="long_distance_fukusho",
            field=models.IntegerField(default=0, verbose_name="中長距離複勝数"),
        ),
        migrations.AddField(
            model_name="horseanalysis",
            name="long_distance_fukusho_rate",
            field=models.FloatField(default=0, verbose_name="中長距離複勝率"),
        ),
        migrations.AddField(
            model_name="horseanalysis",
            name="long_distance_rentai",
            field=models.IntegerField(default=0, verbose_name="中長距離連対数"),
        ),
        migrations.AddField(
            model_name="horseanalysis",
            name="long_distance_rentai_rate",
            field=models.FloatField(default=0, verbose_name="中長距離連対率"),
        ),
        migrations.AddField(
            model_name="horseanalysis",
            name="long_distance_starts",
            field=models.IntegerField(default=0, verbose_name="中長距離出走回数"),
        ),
        migrations.AddField(
            model_name="horseanalysis",
            name="long_distance_win_rate",
            field=models.FloatField(default=0, verbose_name="中長距離勝率"),
        ),
        migrations.AddField(
            model_name="horseanalysis",
            name="long_distance_wins",
            field=models.IntegerField(default=0, verbose_name="中長距離勝利数"),
        ),
    ]
