# Generated by Django 5.0 on 2024-12-09 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0002_horseanalysis_long_distance_fukusho_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HorseRacingData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("excel_file", models.FileField(upload_to="racing_data/")),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="RaceResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("horse_name", models.CharField(max_length=100)),
                ("race_date", models.CharField(max_length=20)),
                ("race_name", models.CharField(max_length=100)),
                ("rank", models.CharField(max_length=10)),
                ("distance", models.CharField(max_length=20)),
                ("course_type", models.CharField(max_length=10)),
                ("track_condition", models.CharField(max_length=10)),
                ("time", models.CharField(max_length=20)),
                ("jockey", models.CharField(max_length=50)),
                ("weight", models.CharField(max_length=10)),
                ("odds", models.CharField(max_length=10)),
                ("last_3f", models.CharField(max_length=10)),
                ("passing_order", models.CharField(max_length=50)),
                (
                    "uploaded_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.horseracingdata",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="HorseAnalysis",
        ),
    ]
